name: openwpmdata
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.11.0,<3.12
  - plyvel >=1.5.0,<2
  - nodejs >=18.12.1,<19
  - requests >=2.28.2,<3
  - ipykernel >=6.21.1
  - ipython-sql >=0.3.9
  - SQLAlchemy >=1.4.46,<2
  - pyright >=1.1.295,
  - scikit-learn >=1.2.1
  - pandas >=1.5.3
  - pandas-stubs >=1.5.3.230214
  