name: openwpmdata
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.0.5
  - backcall=0.2.0
  - blas=1.0
  - bottleneck=1.3.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=38.0.1
  - debugpy=1.5.1
  - decorator=5.1.1
  - editorconfig=0.12.3
  - entrypoints=0.4
  - executing=0.8.3
  - icu=68.1
  - idna=3.4
  - importlib-metadata=5.0.0
  - intel-openmp=2021.4.0
  - ipykernel=6.15.2
  - ipython=8.4.0
  - ipython-sql=0.3.9
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jsbeautifier=1.14.0
  - jupyter_client=7.3.5
  - jupyter_core=4.11.1
  - ld_impl_linux-64=2.38
  - leveldb=1.23
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.0.3
  - libuv=1.40.0
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - nodejs=16.13.1
  - numexpr=2.8.3
  - numpy=1.23.3
  - numpy-base=1.23.3
  - openssl=1.1.1s
  - packaging=21.3
  - pandas=1.4.4
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.2.2
  - plyvel=1.4.0
  - prettytable=3.4.1
  - prompt-toolkit=3.0.20
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.10.6
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytz=2022.1
  - pyzmq=23.2.0
  - readline=8.2
  - requests=2.28.1
  - setuptools=65.5.0
  - six=1.16.0
  - snappy=1.1.9
  - sqlalchemy=1.3.24
  - sqlite=3.39.3
  - sqlparse=0.4.3
  - stack_data=0.2.0
  - tk=8.6.12
  - tornado=6.2
  - traitlets=5.1.1
  - tzdata=2022f
  - urllib3=1.26.13
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.6
  - zeromq=4.3.4
  - zipp=3.10.0
  - zlib=1.2.13
