name: Python pyright Typecheck
on: [push]
jobs:
  pyright Typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      # - name: pyright type check
      #   uses: jakebailey/pyright-action@v1
      - name : micromamba install
        run : bash -i scripts/micromamba-install.sh
      - name: install & activate environment
        run : source ~/.bashrc
        run : eval "$(micromamba shell hook --shell=bash)"
        run : micromamba create -f environment.yaml
        run : micromamba activate openwpmdata
      - name : pyright Typecheck
        run : pyright