name: Python pyright Typecheck
on: [push]
jobs:
  pyright Typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: pyright type check
        uses: jakebailey/pyright-action@v1