name: Python pyright Typecheck
on: [push]
jobs:
  pyright-typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name : micromamba install
        run : bash scripts/micromamba-install.sh
      - name : install environment
        run: bash scripts/install.sh
      - name : pyright Typecheck
        run : bash scripts/pyright-run.sh